// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microzone.SprintManager.Infrastructure.Data;

#nullable disable

namespace Microzone.SprintManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SprintManagerDbContext))]
    [Migration("20260704102906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.GroomingParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroomingSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroomingSessionId", "UserId")
                        .IsUnique();

                    b.ToTable("GroomingParticipants");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.GroomingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentTicketIndex")
                        .HasColumnType("int");

                    b.Property<int>("SprintId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VotesRevealed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("GroomingSessions");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.GroomingVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroomingSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("SprintTicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeightValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SprintTicketId");

                    b.HasIndex("UserId");

                    b.HasIndex("GroomingSessionId", "SprintTicketId", "UserId")
                        .IsUnique();

                    b.ToTable("GroomingVotes");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(2870),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(3813),
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(4124),
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroomingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SprintId")
                        .HasColumnType("int");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TimeScore")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrelloCardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WeightValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SprintId", "TrelloCardId")
                        .IsUnique();

                    b.ToTable("SprintTickets");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicketAssignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SprintTicketId")
                        .HasColumnType("int");

                    b.Property<string>("TrelloMemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SprintTicketId");

                    b.ToTable("SprintTicketAssignees");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SprintTicketId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SprintTicketId");

                    b.ToTable("SprintTicketComments");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicketLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SprintTicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SprintTicketId");

                    b.ToTable("SprintTicketLabels");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SystemDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9415),
                            Name = "PROMAN - IAR NC"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9918),
                            Name = "PROMAN - PW NC"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9931),
                            Name = "PROMAN - DASHBOARD"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9939),
                            Name = "PROMAN GENERAL"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9946),
                            Name = "PROMAN - ROADS NC"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9966),
                            Name = "DOCSIGN - APP"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9977),
                            Name = "PROMAN - IDENTITY"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9989),
                            Name = "PROMAN - ADMIN"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 680, DateTimeKind.Utc).AddTicks(9998),
                            Name = "SMOKE SIGNAL - APP"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 681, DateTimeKind.Utc).AddTicks(14),
                            Name = "PROMAN - PORTFOLIO MANAGEMENT (UAMP)"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 681, DateTimeKind.Utc).AddTicks(24),
                            Name = "CRICKET CLINIC"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 681, DateTimeKind.Utc).AddTicks(35),
                            Name = "PROMAN - CALL LOGS NC"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 681, DateTimeKind.Utc).AddTicks(46),
                            Name = "ROADS - APP"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 681, DateTimeKind.Utc).AddTicks(56),
                            Name = "PROMAN - FILE SYSTEM"
                        });
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.TrelloBoardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SystemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TrelloBoardConfigs");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.TrelloImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportedTicketCount")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SprintId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsedMockData")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("TrelloImportRuns");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.WeightCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeightValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeightCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 678, DateTimeKind.Utc).AddTicks(2227),
                            Element = "Lightning",
                            EstimatedTime = "Half Day",
                            Line = "Blink and it's done.",
                            TimeLabel = "Super Quick Fix",
                            TimeScore = 0,
                            WeightValue = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 678, DateTimeKind.Utc).AddTicks(6384),
                            Element = "Water",
                            EstimatedTime = "1 day",
                            Line = "Smooth and steady.",
                            TimeLabel = "Quick Fix",
                            TimeScore = 1,
                            WeightValue = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 678, DateTimeKind.Utc).AddTicks(6409),
                            Element = "Plant",
                            EstimatedTime = "2 - 3 days",
                            Line = "Needs room to grow.",
                            TimeLabel = "Medium Fix",
                            TimeScore = 2,
                            WeightValue = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 678, DateTimeKind.Utc).AddTicks(6412),
                            Element = "Fire",
                            EstimatedTime = "3 - 4 days",
                            Line = "This one brings heat.",
                            TimeLabel = "Long Fix",
                            TimeScore = 3,
                            WeightValue = 8
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 4, 10, 29, 4, 678, DateTimeKind.Utc).AddTicks(6415),
                            Element = "Rock",
                            EstimatedTime = "5 - 12 days",
                            Line = "Hard as a rock.",
                            TimeLabel = "Super Fix",
                            TimeScore = 4,
                            WeightValue = 13
                        });
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.GroomingParticipant", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.GroomingSession", "GroomingSession")
                        .WithMany("Participants")
                        .HasForeignKey("GroomingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microzone.SprintManager.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroomingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.GroomingSession", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.GroomingVote", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.GroomingSession", "GroomingSession")
                        .WithMany("Votes")
                        .HasForeignKey("GroomingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microzone.SprintManager.Domain.Entities.SprintTicket", "SprintTicket")
                        .WithMany()
                        .HasForeignKey("SprintTicketId")
                        .IsRequired();

                    b.HasOne("Microzone.SprintManager.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroomingSession");

                    b.Navigation("SprintTicket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicket", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Tickets")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicketAssignee", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.SprintTicket", "SprintTicket")
                        .WithMany("Assignees")
                        .HasForeignKey("SprintTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintTicket");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicketComment", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.SprintTicket", "SprintTicket")
                        .WithMany("Comments")
                        .HasForeignKey("SprintTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintTicket");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicketLabel", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.SprintTicket", "SprintTicket")
                        .WithMany("Labels")
                        .HasForeignKey("SprintTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintTicket");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.TrelloImportRun", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Microzone.SprintManager.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microzone.SprintManager.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.GroomingSession", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.SprintTicket", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Comments");

                    b.Navigation("Labels");
                });

            modelBuilder.Entity("Microzone.SprintManager.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
